apiVersion: v1
kind: Pod
metadata:
  name: slackbot
  labels:
    app.kubernetes.io/name: Slackbot
spec:
  containers:
  - name: slackbot
    image: fredhsu/slackbot
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: slackbot-service
spec:
  selector:
    app.kubernetes.io/name: Slackbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
